# Generated by Django 5.2.17 on 2026-08-19 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_productvariation_productimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False)),
                ('min_select', models.PositiveIntegerField(default=0)),
                ('max_select', models.PositiveIntegerField(default=1)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('addon_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='catalog.product')),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_links', to='catalog.product')),
            ],
            options={
                'db_table': 'product_addons',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('parent_product', 'addon_product')},
            },
        ),
    ]
