# Generated by Django 5.2.17 on 2026-08-19 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productaddon'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_qty', models.IntegerField()),
                ('reason', models.CharField(max_length=100)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='catalog.productvariation')),
            ],
            options={
                'db_table': 'inventory_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
