# Generated by Django 5.2.17 on 2026-08-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_product_categories_m2m"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("customer_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=32)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stock_notifications", to="catalog.product")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="stock_notifications", to=settings.AUTH_USER_MODEL)),
                ("variation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stock_notifications", to="catalog.productvariation")),
            ],
            options={"db_table": "stock_notifications", "ordering": ["-created_at"]},
        ),
    ]
